#!/usr/bin/python2.
# encoding=utf-8

import lmysqlNetatmo


user		="mdaniele"
password	="Esedra#84"
host		="127.0.0.1"
database	="netatmo"

mysqlObj = lmysqlNetatmo.mysqlLib( user,password, host, database)

mysqlObj.openConnection()
# mysqlObj.checkUser()
id_station = "AA:AA:BB:CC:DD"
exist=mysqlObj.checkStation(id_station)

if(exist ==0):
	mysqlObj.insertStation()


mysqlObj.closeConnection()